variables:
  VITE_APP_VERSION: $CI_COMMIT_SHORT_SHA

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm  --version
    - npm  ci
    - npm  run build
  artifacts:
    paths:
      - build/

aws_s3:
  stage: deploy
  image: 
    name: amazon/aws-cli:2.27.45
    entrypoint: ['']
  script:
    - aws --version
    - aws s3 ls
    - echo "<h1>This is coming from GitLab CI/CD Course</h1>" > index.html
    - aws s3 cp index.html s3://sa-bucket-virginia123/index.html
    - aws s3 sync ./build/ s3://sa-bucket-virginia123